[package]
name = "eval"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
memory = { path = "../memory" }
anyhow = { workspace = true }
